version: '3.9'

services:
  landing:
    build:
      context: ./landing
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    env_file:
      # - ./landing/.env
      - .env
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    networks:
      - app
    command: >
      sh -c "
      pnpm run start -p ${FRONTEND_PORT}
      "

  backend:
    build:
      context: ./backend
      args:
        DATABASE_URL: ${DATABASE_URL}
    env_file:
      - ./backend/.env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - app
    command: >
      sh -c "
      pnpm prisma migrate deploy &&
      pnpm run start
      "


  db:
    image: postgres:15
    ports:
      - "${DB_PORT}:5432"  # Optional for local DB tool access
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - nestjs_demo_data:/var/lib/postgresql/data
    networks:
      - app

volumes:
  nestjs_demo_data:

networks:
  app:
    driver: bridge
